## Import Libraries

In [1]:
import pandas as pd 
from selenium import webdriver
from bs4 import BeautifulSoup
import time

## Load Data

In [2]:
df = pd.read_csv("Skincare Dataset/wrinkle.csv")
df = df.loc[:, ~df.columns.str.contains("^Unnamed: 0")]

df.head(10)

,problem,ingredient,product name,product link
0,wrinkles,tretinoin,A-Ret Tretinoin 0.1%,https://inkeedecoder.com/products/a-ret-tretin...
1,wrinkles,tretinoin,A-Ret Tretinoin Gel 0.05%,https://inkeedecoder.com/products/a-ret-tretin...
2,wrinkles,tretinoin,ASSOS Tre® %0.05 Krem,https://inkeedecoder.com/products/assos-tre-r-...
3,wrinkles,tretinoin,Abdiibrahim Acnelyse,https://inkeedecoder.com/products/abdiibrahim-...
4,wrinkles,tretinoin,Acnelyse Tretinoin %0.025,https://inkeedecoder.com/products/acnelyse-tre...
5,wrinkles,tretinoin,Acnelyse Tretinoin %0.05,https://inkeedecoder.com/products/acnelyse-tre...
6,wrinkles,tretinoin,Acretin 0.05% Tretinoin Cream,https://inkeedecoder.com/products/acretin-0-05...
7,wrinkles,tretinoin,Acretin Tretinoin 0.025% Cream,https://inkeedecoder.com/products/acretin-tret...
8,wrinkles,tretinoin,"Actavis Pharma, Inc. Actavis Tretinoin Cream, ...",https://inkeedecoder.com/products/actavis-phar...
9,wrinkles,tretinoin,Airol cream 0.5 Airol Cream,https://inkeedecoder.com/products/airol-cream-...

##### Membuat Driver untuk Chrome Browser

In [3]:
driver = webdriver.Chrome()

##### Scraping Data

In [4]:
for index, row in df.iterrows():
    url = row["product link"]

    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    ingredient_elements = soup.select("a.ingred-link")

    ingredients = []

    for ing in ingredient_elements:
        ingredient_name = ing.get_text(strip=True)

        if ingredient_name not in ingredients:
            ingredients.append(ingredient_name)

    if len(ingredients) > 0:
        df.loc[index, "ingredient"] = ", ".join(ingredients)

    print("Product:", row["product name"])
    print("Link:", url)
    print("Jumlah ingredient:", len(ingredients))
    print("Ingredient:", ingredients)
    print("-" * 50)
    
driver.quit()

Product: A-Ret Tretinoin 0.1%
Link: https://inkeedecoder.com/products/a-ret-tretinoin-0-1
Jumlah ingredient: 8
Ingredient: ['Tretinoin', 'Propylene Glycol', 'Isopropanol', 'Carbomer', 'Triethanolamine', 'Butylated Hydroxytoluene', 'Methyl Hydroxybenzoate', 'Propyl Hydroxybenzoate']
--------------------------------------------------
Product: A-Ret Tretinoin Gel 0.05%
Link: https://inkeedecoder.com/products/a-ret-tretinoin-gel-0-05
Jumlah ingredient: 11
Ingredient: ['Tretinoin', 'PEG-4 Olivate', 'Olive Oil PEG-7 Esters', 'Methyl Hydroxybenzoate', 'Propyl Hydroxybenzoate', 'Propylene Glycol', 'Silicon Oil', 'Caprylic/\u200bCapric Triglyceride', 'Carbomer', 'Triethanolamine', 'Purified Water']
--------------------------------------------------
Product: ASSOS Tre® %0.05 Krem
Link: https://inkeedecoder.com/products/assos-tre-r-0-05-krem
Jumlah ingredient: 13
Ingredient: ['Retinoic Acid Tretinoin (0.5)', 'Isopropyl Myristate', 'Carbopol 974 Polymer', 'Polysorbate 80', 'Glycerol', 'Triglyceride', 'Light Liquid Vaseline', 'Butylated Hydroxytoluene', 'Butylated Hydroxy Anisole', 'Methylparaben', 'Propylparaben', 'Sodium Hydroxide', 'Aqua']
--------------------------------------------------
Product: Abdiibrahim Acnelyse
Link: https://inkeedecoder.com/products/abdiibrahim-acnelyse
Jumlah ingredient: 10
Ingredient: ['Tretinoin', 'Cetyl Alcohol', 'Stearyl Alcohol', 'Tween 60', 'Sorbitan Monostearate', 'Methylparaben', 'Propylparaben', 'BHT', 'Propylene Glycol', 'Deionized-Water']
--------------------------------------------------
Product: Acnelyse Tretinoin %0.025
Link: https://inkeedecoder.com/products/acnelyse-tretinoin-0-025
Jumlah ingredient: 7
Ingredient: ['Tretinoin (0.025)', 'Butylhydroxytoluene (E321)', 'Cetyl Alcohol', 'Methyl Parahydroxybenzoate (E218)', 'Propyl Parahydroxybenzoate (E216)', 'Propylene Glycol', 'Stearyl Alcohol']
--------------------------------------------------
Product: Acnelyse Tretinoin %0.05
Link: https://inkeedecoder.com/products/acnelyse-tretinoin-0-05
Jumlah ingredient: 11
Ingredient: ['Tretinoin (0,05%)', 'Butylhydroxytoluene (E321)', 'Paraffin (Vaseline Flant)', 'Polysorbate 60', 'Cetyl Alcohol', 'Methyl Parahydroxybenzoate (E218)', 'Propyl Parahydroxybenzoate (E216)', 'Propylene Glycol', 'Sorbitan Stearate (Span 60)', 'Stearyl Alcohol', 'Purified Water']
--------------------------------------------------
Product: Acretin 0.05% Tretinoin Cream
Link: https://inkeedecoder.com/products/acretin-0-05-tretinoin-cream
Jumlah ingredient: 9
Ingredient: ['Tretinoin (0.05%)', 'Polyoxyl 40 Stearate', 'Stearyl Alcohol', 'Isopropyl Myristate', 'Stearic Acid', 'BHT', 'Sorbic Acid', 'Xanthan Gum', 'Purified Water']
--------------------------------------------------
Product: Acretin Tretinoin 0.025% Cream
Link: https://inkeedecoder.com/products/acretin-tretinoin-0-025-cream
Jumlah ingredient: 13
Ingredient: ['Tretinoin (0.025%)', 'Stearyl Alcohol', 'Isopropyl Myristate', 'Propylene Glycol', 'Polysorbate 60', 'Sorbitan Monostearate', 'Glycerin', 'Carbomer', 'Edetate Disodium', 'Methylparaben', 'Propylparaben', 'Butylated Hydroxytoluene', 'Water']
--------------------------------------------------
Product: Actavis Pharma, Inc. Actavis Tretinoin Cream, USP 0.025%
Link: https://inkeedecoder.com/products/actavis-pharma-inc-actavis-tretinoin-cream-usp-0-025
Jumlah ingredient: 11
Ingredient: ['Tretinoin (0.025%)', 'Stearic Acid', 'Polyolprepolymer-2', 'Isopropyl Myristate', 'Polyoxyl 40 Stearate', 'Propylene Glycol', 'Stearyl Alcohol', 'Xanthan Gum', 'Sorbic Acid', 'Butylated Hydroxytoluene', 'Purified Water']
--------------------------------------------------
Product: Airol cream 0.5 Airol Cream
Link: https://inkeedecoder.com/products/airol-cream-0-5-airol-cream
Jumlah ingredient: 2
Ingredient: ['Tretinoin (0.5 Mg)', 'Butylhydroxyanisole (E320) (X)']
--------------------------------------------------
Product: Airol cream 0.5 Tretinoina
Link: https://inkeedecoder.com/products/airol-cream-0-5-tretinoina
Jumlah ingredient: 11
Ingredient: ['Tretinoin', 'Glycerol Stearate', 'Ceteareth-20', 'Sorbitol Solution (70%)', 'Cetyl Esters Wax', 'Phytosqualene', 'Butylhydroxyanisole (E320)', 'Disodium Edetate', 'Magnesium Sulfate Heptahydrate', 'Benzoic Acid (E210)', 'Purified Water']
--------------------------------------------------
Product: Andrómaco Hidrosam T 0,010%
Link: https://inkeedecoder.com/products/andromaco-hidrosam-t-0-010
Jumlah ingredient: 17
Ingredient: ['Tretinoin (0.01%)', 'Soluble Collagen', 'Elastin', 'Glyceryl Monostearate', 'Cetyl Alcohol', 'Stearyl Alcohol', 'Octyldodecanol', 'Methyl Paraben', 'Propyl Paraben', 'Carbopol', 'Trietanolamin (C.S.P Ph 7)', 'Perfum', 'Imidurea', 'BHT', 'BHA', 'Propylenglycol', 'Purified Water']
--------------------------------------------------
Product: Andrómaco Hidrosam T 0,025%
Link: https://inkeedecoder.com/products/andromaco-hidrosam-t-0-025
Jumlah ingredient: 17
Ingredient: ['Tretinoin (0.025%)', 'Soluble Collagen', 'Elastin', 'Glyceryl Monostearate', 'Cetyl Alcohol', 'Stearyl Alcohol', 'Octyldodecanol', 'Methyl Paraben', 'Propyl Paraben', 'Carbopol', 'Trietanolamin (C.S.P Ph 7)', 'Perfum', 'Imidurea', 'BHT', 'BHA', 'Propylenglycol', 'Purified Water']
--------------------------------------------------
Product: Andrómaco Hidrosam T 0,050%
Link: https://inkeedecoder.com/products/andromaco-hidrosam-t-0-050
Jumlah ingredient: 17
Ingredient: ['Tretinoin (0,05%)', 'Soluble Collagen', 'Elastin', 'Glyceryl Monostearate', 'Cetyl Alcohol', 'Stearyl Alcohol', 'Octyldodecanol', 'Methyl Paraben', 'Propyl Paraben', 'Carbopol', 'Trietanolamin (C.S.P Ph 7)', 'Perfum', 'Imidurea', 'BHT', 'BHA', 'Propylenglycol', 'Purified Water']
--------------------------------------------------
Product: Andrómaco Hidrosam T 0,100%
Link: https://inkeedecoder.com/products/andromaco-hidrosam-t-0-100
Jumlah ingredient: 17
Ingredient: ['Tretinoin (0,1%)', 'Soluble Collagen', 'Elastin', 'Glyceryl Monostearate', 'Cetyl Alcohol', 'Stearyl Alcohol', 'Octyldodecanol', 'Methyl Paraben', 'Propyl Paraben', 'Carbopol', 'Trietanolamin (C.S.P Ph 7)', 'Perfum', 'Imidurea', 'BHT', 'BHA', 'Propylenglycol', 'Purified Water']
--------------------------------------------------
Product: Apostrophe Tretinoin
Link: https://inkeedecoder.com/products/apostrophe-tretinoin
Jumlah ingredient: 20
Ingredient: ['Tretinoin (0.025% - 0.1%)', 'Niacinamide (4%)', 'Butylated Hydroxytoluene', 'C12-15 Alkyl Benzoate', 'Caprylic/\u200bCapric Triglycerides', 'Cetyl Alcohol', 'Ethylhexylglycerin', 'Glycerin Usp', 'Glyceryl Stearate', 'Hydroxyethyl Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Olive Oil', 'Oleic Acid', 'PEG-100 Stearate', 'Phenoxyethanol', 'Polydimethylsiloxane', 'Purified Water', 'Propylene Glycol', 'Stearic Acid', 'Trolamine', 'Vitamin E']
--------------------------------------------------
Product: Apoteka Dona Hidrofilni Krem Sa Tretinoinom 0.05%
Link: https://inkeedecoder.com/products/apoteka-dona-hidrofilni-krem-sa-tretinoinom-0-05
Jumlah ingredient: 10
Ingredient: ['Tretinoin (0.05%)', 'Aqua', 'Petrolatum', 'Propylene Glycol', 'Caprylic/\u200bCapric Triglyceride', 'Ceteareth-20', 'Cetyl Alcohol', 'Glyceryl Stearate SE', 'Paraffinum Liquidum', 'Butylhydroxytoluene']
--------------------------------------------------
Product: Avalon Pharma Avotin-a
Link: https://inkeedecoder.com/products/avalon-pharma-avotin-a
Jumlah ingredient: 17
Ingredient: ['Tretinoin', 'Ceteareth-6', 'Stearyl Alcohol', 'Ceteareth-25', 'Glyceryl Mono Sterate', 'Cetyl Alcohol', 'Vaseline', 'Yellow 1', 'Beeswax', 'Cetearyl Octanoate', 'Imidurea', 'Methyl Paraben', 'Propylparaben', 'Propylene Glycol', 'Titanium Dioxide', 'Butylated Hydroxy Anisole', 'Purified Water']
--------------------------------------------------
Product: Bailleul Laboratories Tretin® %0,05 Krem
Link: https://inkeedecoder.com/products/bailleul-laboratories-tretin-r-0-05-krem
Jumlah ingredient: 13
Ingredient: ['Retinoic Acid (Tretinoin)', 'Isopropyl Myristate', 'Carbopol Polymer', 'Polysorbate 80', 'Miglyol', 'Glycerol', 'Paraffinum Liquidum', 'Butylated Hydroxytoluene', 'Butylated Hydroxy Anisole', 'Methylparaben', 'Propylparaben', 'Sodium Hydroxide', 'Aqua']
--------------------------------------------------
Product: Bausch Health Retin-A Micro (0.04%)
Link: https://inkeedecoder.com/products/bausch-health-retin-a-micro-0-04
Jumlah ingredient: 14
Ingredient: ['Tretinoin (0.04%)', 'Purified Water', 'Carbomer', 'Glycerin', 'Disodium EDTA', 'Propylene Glycol', 'Propylene Glycol Dicaprylate/\u200bDicaprate', 'Sorbic Acid', 'PPG-20 Methyl Glucose Ether Distearate', 'Cyclomethicone', 'Dimethicone Copolyol', 'Benzyl Alcohol', 'Trolamine', 'Butylated Hydroxytoluene']
--------------------------------------------------
Product: Bausch Health Retin-a Cream 0.05%
Link: https://inkeedecoder.com/products/bausch-health-retin-a-cream-0-05
Jumlah ingredient: 9
Ingredient: ['Tretinoin', 'Butylhydroxytoluene', 'Isopropyl Myristate', 'Polyoxyl 40 Stearate', 'Stearic Acid', 'Stearyl Alcohol', 'Sorbic Acid', 'Xanthan Gum', 'Purified Water']
--------------------------------------------------
Product: Bausch Health Retin-a Micro (tretinoin) Gel Microsphere 0.1%
Link: https://inkeedecoder.com/products/bausch-health-retin-a-micro-tretinoin-gel-microsphere-0-1
Jumlah ingredient: 12
Ingredient: ['Tretinoin (0.1%)', 'Water', 'Carbomer (0.1%)', 'Glycerin', 'Disodium EDTA', 'Propylene Glycol', 'Sorbic Acid', 'PPG-20 Methyl Glucose Ether Distearate', 'Dimethicone/\u200bMethicone Copolymer', 'Benzyl Alcohol', 'Triethanolamine', 'BHT']
--------------------------------------------------
Product: Bausch Health Vitamin A Acid Gel (0.05%)
Link: https://inkeedecoder.com/products/bausch-health-vitamin-a-acid-gel-0-05
Jumlah ingredient: 9
Ingredient: ['Tretinoin (0.05%)', 'Alcohol (95%)', 'Carboxyvinyl Polymer', 'Carbopol 980', 'Carbomer', 'Isopropyl Alcohol', 'Propylene Glycol', 'Purified Water', 'Trolamine']
--------------------------------------------------
Product: CCSD Rx Reverse Tretinoin 0.05%
Link: https://inkeedecoder.com/products/ccsd-rx-reverse-tretinoin-0-05
Jumlah ingredient: 18
Ingredient: ['Retinoic Acid (0.05%)', 'Water', 'Caprylic/\u200bCapric Triglycerides', 'Stearyl Alcohol', 'Stearic Acid', 'Glyceryl Stearate', 'PEG-100 Stearate', 'Diisopropyl Dimer Dilinoleate', 'Aluminum', 'Magnesium Silicate', 'Polyoxyethylene 45 (40)', 'Mg Stearate+', 'Benzyl Alcohol', 'Silica Gel', 'Bisabolol', 'Retinoic Acid', 'BHA', 'BHT']
--------------------------------------------------
Product: CTS CHEMICAL INDUSTRIES Ret-Avit Cream 0.05%
Link: https://inkeedecoder.com/products/cts-chemical-industries-ret-avit-cream-0-05
Jumlah ingredient: 12
Ingredient: ['Tretinoin (0.05%)', 'Butylated Hydroxytoluene', 'Cetomacrogol 1000', 'Lanolin Anhydrous', 'Glyceryl Monostearate Se', 'Cetostearyl Alcohol', 'Oleic Acid Decylester', 'Dimethicone 350', 'Sorbitol Solution (70%)', 'Sorbic Acid', 'Potassium Sorbate', 'Purified Water']
--------------------------------------------------
Product: CTS CHEMICAL INDUSTRIES Ret-Avit Gel 0.05%
Link: https://inkeedecoder.com/products/cts-chemical-industries-ret-avit-gel-0-05
Jumlah ingredient: 11
Ingredient: ['Tretinoin (0.05%)', 'Cremophor Rh 40', 'Softigen 767', 'Carbomer 940', 'Butylated Hydroxytoluene', 'Methyl Dihydroxybenzoate', 'Sodium Propyl Hydroxybenzoate', 'Sodium Hydroxide', 'Hydrochloric Acid', 'Isopropyl Alcohol', 'Purified Water']
--------------------------------------------------
Product: Cantabria Labs Neocare 4mg/g cream
Link: https://inkeedecoder.com/products/industrial-farmaceutica-cantabria-neocare
Jumlah ingredient: 12
Ingredient: ['Tretinoin', 'C12-20 Acid PEG-8 Ester', 'Cetyl Alcohol', 'Glycerin', 'Propylene Glycol', 'BHT', 'Ascorbyl Palmitate', 'Glyceryl Stearate', 'Citric Acid', 'Methyl Parahydroxybenzoate (E-219)', 'Propyl Parahydroxybenzoate (E-217)', 'Water']
--------------------------------------------------
Product: Cantabria Labs Retincare
Link: https://inkeedecoder.com/products/cantabria-labs-retincare
Jumlah ingredient: 11
Ingredient: ['Ácido Retinoico', 'Ácido Glicólico', 'Propylene Glycol', 'PEG-7 Glyceryl Cocoate', 'Aminomethyl Propanol', 'Hydroxyethylcellulose', 'Polyvinyl Alcohol', 'Imidazolidinyl Urea', 'Disodium EDTA', 'BHT', 'Aqua']
--------------------------------------------------
Product: Cassará Neotretin M Tretinoína 0,025%
Link: https://inkeedecoder.com/products/cassara-neotretin-m-tretinoina-0-025
Jumlah ingredient: 24
Ingredient: ['Tretinoin (0.025%)', 'Gluconolactone (4%)', 'Ethylhexyl Methoxycinnamate', 'Polydimethylsiloxane', 'Cetyl Alcohol', 'Ceramide', 'Cholesterol', 'Disodium EDTA', 'Perfume', 'Sodium Hydroxide', 'Ascorbic Acid', 'Vitamin E Acetate', 'Glyceryl Monostearate', 'Sodium PCA', 'Hydrogenated Lecithin', 'Propylene Glycol', 'Cetostearyl Alcohol', 'Ceteareth-20', 'Methylparaben', 'Propylparaben', 'Mineral Oil', 'Oat Glycolic Extract', 'Sulibenzone', 'Purified Water']
--------------------------------------------------
Product: Cordes Vas
Link: https://inkeedecoder.com/products/cordes-vas
Jumlah ingredient: 14
Ingredient: ['Tretinoin', 'Butylated Hydroxytoluene', 'Beryl Perfume Oil', 'Cetyl Stearyl Alcohol', 'Trispolyoxyethylenephosphate', 'Citric Acid Monohydrate', 'Glyceryl Monostearate', 'Isopropyl Myristate', 'Palmitoyl Ascorbic Acid', 'Macrogol-7-Glycerol Cocoate', 'Propylene Glycol', 'Sorbitan Stearate', 'Sorbic Acid', 'Purified Water']
--------------------------------------------------
Product: Cordes Vas Creme (0.05 Tretinoin)
Link: https://inkeedecoder.com/products/cordes-vas-creme-0-05-tretinoin
Jumlah ingredient: 13
Ingredient: ['Tretinoin', 'Butylated Hydroxytoluene', 'Cetyl Stearyl Alcohol', 'Citric Acid', 'Glycerin Monostearate', 'Isopropyl Myristate', 'Ascorbyl Palmitate', 'PEG-7 Glyceryl Cocoate', 'Propylene Glycol', 'Sorbitan Stearate', 'Sorbic Acid', 'Purified Water', 'Stearyl Phosphate']
--------------------------------------------------
Product: Dar Al Dawa Smooderm
Link: https://inkeedecoder.com/products/dar-al-dawa-smooderm
Jumlah ingredient: 12
Ingredient: ['Tretinoin (0.05%)', 'Isopropanol', 'Propylene Glycol', 'Cetyl Alcohol', 'Sorbitan Monostearate', 'Polysorbate 20', 'Butylated Hydroxy Anisole', 'Triethanolamine', 'Carbomer', 'Benzyl Alcohol', 'Disodium Edetate', 'Purified Water']
--------------------------------------------------
Product: DermaXP Reticor (tretinoin) cream
Link: https://inkeedecoder.com/products/dermaxp-reticor-tretinoin-cream
Jumlah ingredient: 12
Ingredient: ['Tretinoin (0.025%, 0,05%, 0,1%)', 'Cetostearyl Alcohol', 'Stearyl Alcohol', 'Isopropyl Myristate', 'Polysorbate 60', 'Sorbitan Stearate', 'Butylated Hydroxytoluene', 'Benzoic Acid', 'Disodium Edetate', 'D-Panthenol', 'Purified Water', 'Sodium Hydroxide']
--------------------------------------------------
Product: DermaXP Reticor (tretinoin) gel
Link: https://inkeedecoder.com/products/dermaxp-reticor-tretinoin-gel
Jumlah ingredient: 8
Ingredient: ['Tretinoin (0.05%, 0.1%)', 'Purified Water', 'Diisopropyl Adipate', 'Propylene Glycol', 'Acrylates/\u200bC10-30 Alkyl Acrylate Crosspolymer', 'BHT', 'Methylparaben', 'Sodium Hydroxide']
--------------------------------------------------
Product: Dermatica 0.1% Tretinoin Cream
Link: https://inkeedecoder.com/products/dermatica-0-1-tretinoin-cream
Jumlah ingredient: 10
Ingredient: ['Tretinoin (0.1%)', 'Purified Water', 'Carthamus Tinctorius Oleosomes', 'Polyacrylate-13', 'Polyisobutene', 'Sodium Carbomer', 'Polysorbate 20', 'Tocopheryl Acetate', 'Benzoic Acid (0.1%)', 'Sorbic Acid (0.1%)']
--------------------------------------------------
Product: Dermatica Tretinoin 0.025% + Niacinamide 4%
Link: https://inkeedecoder.com/products/dermatica-tretinoin-0-025
Jumlah ingredient: 18
Ingredient: ['Tretinoin (0.025%)', 'Niacinamide (4%)', 'Aqua', 'Propylene Glycol', 'Glycerin', 'Cetyl Alcohol', 'Glyceryl Stearate', 'PEG-75 Stearate', 'Isohexadecane', 'Isododecane', 'Dimethicone', 'Polyisobutene', 'Polysorbate 20', 'Polyurethane-39', 'Phenoxyethanol', 'Tocopheryl Acetate', 'Sodium Polyacrylate', 'Hydrogenated Farnesene']
--------------------------------------------------
Product: Dermatica Tretinoin 0.05% - Azelaic Acid 15% - Tranexamic Acid 5%
Link: https://inkeedecoder.com/products/dermatica-tretinoin-0-05-azelaic-acid-15-tranexamic-acid-5
Jumlah ingredient: 29
Ingredient: ['Tretinoin', 'Azelaic Acid', 'Tranexamic Acid', 'Purified Water', 'Propylene Glycol', 'Glycerin', 'Panthenol', 'Cetyl Alcohol', 'Glyceryl Stearate', 'Isohexadecane', 'Isododecane', 'C13-15 Alkane', 'Dimethicone', 'Propanediol', 'Polyacrylate-13', 'Polyisobutene', 'Polysorbate 20', 'Polyurethane-39', 'Phenoxyethanol (0.6%)', 'Tocopheryl Acetate', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NP', 'Phytosphingosine', 'Cholesterol', 'Sodium Lauroyl Lactylate', 'Xanthan Gum', 'Carbomer', 'Sodium Hyaluronate']
--------------------------------------------------
Product: Dermatica Tretinoin 0.05% And Niacinamide 4%
Link: https://inkeedecoder.com/products/dermatica-tretinoin-0-05-and-niacinamide-4
Jumlah ingredient: 28
Ingredient: ['Tretinoin', 'Niacinamide', 'Purified Water', 'Propylene Glycol', 'Glycerin', 'Panthenol', 'Cetyl Alcohol', 'Glyceryl Stearate', 'Isohexadecane', 'Isododecane', 'C13-15 Alkane', 'Dimethicone', 'Propanediol', 'Polyacrylate-13', 'Polyisobutene', 'Polysorbate 20', 'Polyurethane-39', 'Phenoxyethanol (0.6%)', 'Tocopheryl Acetate', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NP', 'Phytosphingosine', 'Cholesterol', 'Sodium Lauroyl Lactylate', 'Xanthan Gum', 'Carbomer', 'Sodium Hyaluronate']
--------------------------------------------------
Product: Dermatica Tretinoin 0.1%
Link: https://inkeedecoder.com/products/dermatica-tretinoin-0-1
Jumlah ingredient: 28
Ingredient: ['Tretinoin', 'Niacinamide', 'Purified Water', 'Propylene Glycol', 'Glycerin', 'Panthenol', 'Cetyl Alcohol', 'Glyceryl Stearate', 'Isohexadecane', 'Isododecane', 'C13-15 Alkane', 'Dimethicone', 'Propanediol', 'Polyacrylate-13', 'Polyisobutene', 'Polysorbate 20', 'Polyurethane-39', 'Phenoxyethanol (0.6%)', 'Tocopheryl Acetate', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NP', 'Phytosphingosine', 'Cholesterol', 'Sodium Lauroyl Lactylate', 'Xanthan Gum', 'Carbomer', 'Sodium Hyaluronate']
--------------------------------------------------
Product: Dermatica Tretinoin, Niacinamide 4%, Azelaic Acid 4%
Link: https://inkeedecoder.com/products/dermatica-tretinoin-niacinamide-4-azelaic-acid-4
Jumlah ingredient: 28
Ingredient: ['Tretinoin', 'Niacinamide', 'Azelaic Acid', 'Purified Water', 'Carthamus Tinctorius Oleosomes', 'Propylene Glycol', 'Glycerin', 'Panthenol', 'Polyacrylate-13', 'Polyisobutene', 'Sodium Carbomer', 'Gluconolactone', 'Polysorbate 20', 'Sorbitan Isostearate', 'Benzoic Acid', 'Sorbic Acid', 'Sodium Benzoate', 'Propanediol', 'Tocopheryl Acetate', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NP', 'Phytosphingosine', 'Cholesterol', 'Sodium Lauroyl Lactylate', 'Xanthan Gum', 'Carbomer', 'Sodium Hyaluronate']
--------------------------------------------------
Product: Farmacia cu Traditie Tretinoin 0.025% Cream And Moisture Complex
Link: https://inkeedecoder.com/products/farmacia-cu-traditie-tretinoin-0-025-cream-and-moisture-complex
Jumlah ingredient: 19
Ingredient: ['Tretinoin', 'Aqua', 'Glycerin', 'Coco-Caprylate', 'Cetearyl Olivate', 'Sorbitan Olivate', 'Glyceryl Stearate', 'Stearic Acid', 'Caprylic/\u200bCapric Triglycerides', 'Sodium PCA', 'Urea', 'Trehalose', 'Leuconostoc/\u200bRadish Root Ferment Filtrate', 'Polyquaternium-51', 'Sodium Hyaluronate', 'Phenoxyethanol', 'Ethylhexylglycerin', 'Tocopherol', 'Xanthan Gum']
--------------------------------------------------
Product: Felix Retinoid +
Link: https://inkeedecoder.com/products/felix-retinoid
Jumlah ingredient: 9
Ingredient: ['Tretinoin (0.025%)', 'Clindamycin (1%)', 'Niacinamide (4%)', 'Dimethicone', 'Caprylyl Methicone', 'PEG-12 Dimethicone/\u200bPPG-20 Crosspolymer', 'Butyrospermum Parkii (Shea) Butter', 'Polysilicone-11', 'Tocopheryl Acetate']
--------------------------------------------------

Hal tersebut dilakukan untuk menambahkan kolom `ingredient` yang sebelumnya hanya terdapat 1 untuk setiap kelompok produk. 

Oleh karena itu, scraping data dilakukan agar kolom ingredient per product lebih lengkap dan detail.

Pada masalah kulit pori-pori besar atau pores. Setiap produk mempunyai jumlah yang ingredients yang bervariasi. Satu produk mempunyai sekitar 4 - 110 ingredients yang berbeda-beda.

In [5]:
df.to_csv("Skincare Dataset/wrinkle.csv", index=False)

df.head(10)

,problem,ingredient,product name,product link
0,wrinkles,"Tretinoin, Propylene Glycol, Isopropanol, Carb...",A-Ret Tretinoin 0.1%,https://inkeedecoder.com/products/a-ret-tretin...
1,wrinkles,"Tretinoin, PEG-4 Olivate, Olive Oil PEG-7 Este...",A-Ret Tretinoin Gel 0.05%,https://inkeedecoder.com/products/a-ret-tretin...
2,wrinkles,"Retinoic Acid Tretinoin (0.5), Isopropyl Myris...",ASSOS Tre® %0.05 Krem,https://inkeedecoder.com/products/assos-tre-r-...
3,wrinkles,"Tretinoin, Cetyl Alcohol, Stearyl Alcohol, Twe...",Abdiibrahim Acnelyse,https://inkeedecoder.com/products/abdiibrahim-...
4,wrinkles,"Tretinoin (0.025), Butylhydroxytoluene (E321),...",Acnelyse Tretinoin %0.025,https://inkeedecoder.com/products/acnelyse-tre...
5,wrinkles,"Tretinoin (0,05%), Butylhydroxytoluene (E321),...",Acnelyse Tretinoin %0.05,https://inkeedecoder.com/products/acnelyse-tre...
6,wrinkles,"Tretinoin (0.05%), Polyoxyl 40 Stearate, Stear...",Acretin 0.05% Tretinoin Cream,https://inkeedecoder.com/products/acretin-0-05...
7,wrinkles,"Tretinoin (0.025%), Stearyl Alcohol, Isopropyl...",Acretin Tretinoin 0.025% Cream,https://inkeedecoder.com/products/acretin-tret...
8,wrinkles,"Tretinoin (0.025%), Stearic Acid, Polyolprepol...","Actavis Pharma, Inc. Actavis Tretinoin Cream, ...",https://inkeedecoder.com/products/actavis-phar...
9,wrinkles,"Tretinoin (0.5 Mg), Butylhydroxyanisole (E320)...",Airol cream 0.5 Airol Cream,https://inkeedecoder.com/products/airol-cream-...

Data yang sudah di scraping disimpan dan diperbarui ke dalam bentuk csv agar dapat di masukkan ke database supabase

Terlihat dari 10 hasil awal yang di tampilkan setiap produk memiliki ingredient yang berbeda-beda.