## Import Libraries

In [ ]:
import pandas as pd 
from selenium import webdriver
from bs4 import BeautifulSoup
import time

## Load Data

In [2]:
df = pd.read_csv("Skincare Dataset/Dark-Spots Product.csv")
df = df.loc[:, ~df.columns.str.contains("^Unnamed: 0")]

df.head(10)

,problem,ingredient,product name,product link
0,dark spots,4-butylresorcinol,0.3% | Enlighten Skin Brightener Spf35\n ...,https://inkeedecoder.com/products/neostrata-en...
1,dark spots,acetyl-glucosamine,8.0% | Enlighten Skin Brightener Spf35\n ...,https://inkeedecoder.com/products/neostrata-en...
2,dark spots,acetyl-glucosamine,2.0% | Lab. Restoring Brightening Serum\n ...,https://inkeedecoder.com/products/purid-lab-re...
3,dark spots,alpha-arbutin,2.0% | Alpha Arbutin Brightening Serum\n ...,https://inkeedecoder.com/products/inkey-list-a...
4,dark spots,alpha-arbutin,2.0% | Ascorbic Acid 8% + Alpha Arbutin 2%\n ...,https://inkeedecoder.com/products/the-ordinary...
5,dark spots,azelaic-acid,20.0% | Azelaic Acid\n \n\n ...,https://inkeedecoder.com/products/derma-forte-...
6,dark spots,azelaic-acid,15.0% | Azelaic Acid Control Facial Acne Gel\n...,https://inkeedecoder.com/products/aisuanis-emp...
7,dark spots,azelaic-acid,10.0% | Empowerment Azelaic Acid Sebamed Clear...,https://inkeedecoder.com/products/aisuanis-emp...
8,dark spots,azelaic-acid,10.0% | Professional 10% Azelaic Acid Face Ser...,https://inkeedecoder.com/products/bielenda-pro...
9,dark spots,azelaic-acid,10.0% | Azelaic Acid 10% Serum\n \n\n ...,https://inkeedecoder.com/products/cos-de-baha-...

Dari 10 data awal yang ditampilkan terlihat ada 4 kolom yaitu :

- `Problem` : menunjukkan jenis permasalahan kulit data tersebut adalah dark spots.

- `ingredient` : bahan apa saja yang terkandung dalam setiap produk.

- `Product Name` : nama produk yang sesuai dengan permasalah kulit tersebut.

- `Product_link` : berisi link dari produk yang akan menampilkan gambar dan detail produk tersebut.

##### Membuat Driver untuk Chrome Browser

In [4]:
driver = webdriver.Chrome()

##### Scraping Data

In [5]:
for index, row in df.iterrows():
    url = row["product link"]

    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source, "html.parser")

    ingredient_elements = soup.select("a.ingred-link")

    ingredients = []

    for ing in ingredient_elements:
        ingredient_name = ing.get_text(strip=True)

        if ingredient_name not in ingredients:
            ingredients.append(ingredient_name)

    if len(ingredients) > 0:
        df.loc[index, "ingredient"] = ", ".join(ingredients)

    print("Product:", row["product name"])
    print("Link:", url)
    print("Jumlah ingredient:", len(ingredients))
    print("Ingredient:", ingredients)
    print("-" * 50)
    
driver.quit()

Product: 0.3% | Enlighten Skin Brightener Spf35


            Neostrata
Link: https://inkeedecoder.com/products/neostrata-enlighten-skin-brightener-spf35
Jumlah ingredient: 33
Ingredient: ['Avobenzone 3.0%', 'Octinoxate 7.5%', 'Octisalate 5.0%', 'Aqua/\u200bWater/\u200bEau', 'Acetyl Glucosamine 8.0%', 'Butyloctyl Salicylate', 'Dimethicone', 'C12-15 Alkyl Benzoate', 'Glycerin', 'Cyclopentasiloxane', 'Glyceryl Stearate', 'Butylene Glycol', 'Cyclohexasiloxane', 'Octyldodecyl Neopentanoate', 'Cetyl Alcohol', 'PEG-100 Stearate', 'Cetearyl Alcohol', 'Tocopheryl Acetate', 'Vitis Vinifera (Grape) Seed Extract 1.0%', 'Tetrahydrodiferuloylmethane 0.25%', '4-Butylresorcinol 0.3%', 'Ceteth-20', 'PEG-75 Stearate', 'Propylene Glycol', 'Disodium EDTA', 'Steareth-20', 'Xanthan Gum', 'Ammonium Hydroxide', 'Sodium Bisulfite', 'Carbomer', 'Caprylyl Glycol', 'Phenoxyethanol', 'Chlorphenesin']
--------------------------------------------------
Product: 8.0% | Enlighten Skin Brightener Spf35


            Neostrata
Link: https://inkeedecoder.com/products/neostrata-enlighten-skin-brightener-spf35
Jumlah ingredient: 33
Ingredient: ['Avobenzone 3.0%', 'Octinoxate 7.5%', 'Octisalate 5.0%', 'Aqua/\u200bWater/\u200bEau', 'Acetyl Glucosamine 8.0%', 'Butyloctyl Salicylate', 'Dimethicone', 'C12-15 Alkyl Benzoate', 'Glycerin', 'Cyclopentasiloxane', 'Glyceryl Stearate', 'Butylene Glycol', 'Cyclohexasiloxane', 'Octyldodecyl Neopentanoate', 'Cetyl Alcohol', 'PEG-100 Stearate', 'Cetearyl Alcohol', 'Tocopheryl Acetate', 'Vitis Vinifera (Grape) Seed Extract 1.0%', 'Tetrahydrodiferuloylmethane 0.25%', '4-Butylresorcinol 0.3%', 'Ceteth-20', 'PEG-75 Stearate', 'Propylene Glycol', 'Disodium EDTA', 'Steareth-20', 'Xanthan Gum', 'Ammonium Hydroxide', 'Sodium Bisulfite', 'Carbomer', 'Caprylyl Glycol', 'Phenoxyethanol', 'Chlorphenesin']
--------------------------------------------------
Product: 2.0% | Lab. Restoring Brightening Serum


            Purid
Link: https://inkeedecoder.com/products/purid-lab-restoring-brightening-serum
Jumlah ingredient: 17
Ingredient: ['Water', 'Niacinamide 5.0%', 'Arbutin 2.0%', 'Acetyl Glucosamine 2.0%', 'Bis-Ethoxydiglycol Cyclohexane 1,4-Dicarboxylate 1.0%', 'Pentylene Glycol', 'Butylene Glycol', 'Sophora Flavescens Root Extract**', 'Glycyrrhiza Inflata Root Extract**', 'Scutellaria Baicalensis Root Extract**', 'Dimethicone', 'Sodium Polyacrylate', 'C18-21 Alkane', 'Trideceth-6', '1,2-Hexanediol', 'Hydroxyacetophenone', 'Chlorphenesin']
--------------------------------------------------
Product: 2.0% | Alpha Arbutin Brightening Serum


            The Inkey List
Link: https://inkeedecoder.com/products/inkey-list-alpha-arbutin
Jumlah ingredient: 22
Ingredient: ['Water', 'Butylene Glycol', 'Propanediol', 'Glycerin', 'Alpha-Arbutin 2.0%', 'Dicaprylyl Carbonate', 'Caprylic/\u200bCapric Triglyceride', 'Leuconostoc/\u200bRadish Root Ferment Filtrate', 'Hyaluronic Acid', 'Phenoxyethanol', 'Hydroxyethyl Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Caprylyl Glycol', 'Squalane 0.5%', 'Phospholipids', 'Glycine Soja (Soybean) Extract', 'Carbomer', 'Polysorbate 60', 'Disodium EDTA', 'Sodium Hydroxide', 'Glycolipids', 'Glycine Soja (Soybean) Sterols', 'Tetrapeptide -30']
--------------------------------------------------
Product: 2.0% | Ascorbic Acid 8% + Alpha Arbutin 2%


            The Ordinary
Link: https://inkeedecoder.com/products/the-ordinary-ascorbic-acid-8-alpha-arbutin-2
Jumlah ingredient: 3
Ingredient: ['Propanediol', 'Ascorbic Acid 8.0%', 'Alpha-Arbutin 2.0%']
--------------------------------------------------
Product: 20.0% | Azelaic Acid


            Derma Forte
Link: https://inkeedecoder.com/products/derma-forte-azelaic-acid
Jumlah ingredient: 14
Ingredient: ['Water', 'Azelaic Acid 20.0%', 'Ascorbic Acid', 'Tocopherol', 'Collagen', 'Ubiquinone', 'Carbomer', 'Squalane', 'Centella Asiatica Extract', 'Curcuma Longa Root Extract', 'Glycolic Acid', 'Sodium Hydroxide', 'EDTA', 'Potassium Sorbate']
--------------------------------------------------
Product: 15.0% | Azelaic Acid Control Facial Acne Gel


            Aisuanis
Link: https://inkeedecoder.com/products/aisuanis-empowerment-azelaic-acid-control-facial-acne-gel
Jumlah ingredient: 17
Ingredient: ['Aqua', 'Propylene Glycol', 'Azelaic Acid 15.0%', 'Tetrahydroxypropyl Ethylenediamine', 'Potassium Azeloyl Diglycinate 5.0%', 'Polyacrylate Crosspolymer-6', 'Salicylic Acid 2.0%', 'Lactobionic Acid', 'Bisabolol', 'Gluconolactone', 'Arginine', 'Quaternium-73', 'Dipotassium Glycyrrhizate', '1,2-Hexanediol', 'Isopentyldiol', 'O- Cymen-5-Ol', 'Hydroxyacetophenone']
--------------------------------------------------
Product: 10.0% | Empowerment Azelaic Acid Sebamed Clear Face Facial Cream


            Aisuanis
Link: https://inkeedecoder.com/products/aisuanis-empowerment-azelaic-acid-sebamed-clear-face-facial-cream
Jumlah ingredient: 27
Ingredient: ['Aqua', 'Dipropylene Glycol', 'Cyclopentasiloxane', 'Azelaic Acid 10.0%', 'Lauryl PEG-9 Polydimethylsiloxyethyl Dimethicone', 'Dimethicone', 'Phenyl Trimethicone', 'Polyglyceryl-4 Isostearate', 'Sodium Hydroxide', 'Squalane', 'Salicylic Acid 1.0%', 'Mandelic Acid', 'Potassium Azeloyl Diglycinate', 'Panthenol', 'Niacinamide', 'Stephania Tetrandra Extract', 'Beta-Sitosterol', 'Arginine', 'Tremella Fuciformis (Mushroom) Extract', 'Butylene Glycol', 'Sodium Hyaluronate', 'Magnesium Stearate', 'Hydroxyacetophenone', '1,2-Hexanediol', 'Quaternium-73', 'Pentylene Glycol', 'Hydroxyphenyl Propamidobenzoic Acid']
--------------------------------------------------
Product: 10.0% | Professional 10% Azelaic Acid Face Serum


            Bielenda
Link: https://inkeedecoder.com/products/bielenda-professional-10-azaleic-acid-face-serum
Jumlah ingredient: 12
Ingredient: ['Aqua (Water)', 'Propylene Glycol', 'Azelaic Acid 10.0%', 'Caprylic/\u200bCapric Triglyceride', 'Stearyl Alcohol', 'Betaine', 'Glycerin', 'Ceteareth-20', 'Allantoin', 'Polyacrylate Crosspolymer-6', 'Disodium EDTA', 'Methylparaben']
--------------------------------------------------
Product: 10.0% | Azelaic Acid 10% Serum


            Cos De BAHA
Link: https://inkeedecoder.com/products/cos-de-baha-azelaic-acid-10-serum
Jumlah ingredient: 14
Ingredient: ['Aloe Barbadensis Leaf Extract', 'Propylene Glycol', 'Azelaic Acid 10.0%', 'Polysorbate 20', '1,2-Hexanediol', 'Propanediol', 'Panthenol', 'Niacinamide', 'Sodium Hyaluronate 0.2%', 'Hamamelis Virginiana (Witch Hazel) Leaf Extract', 'Rosmarinus Officinalis (Rosemary) Extract', 'Eucalyptus Globulus Leaf Extract', 'Thymus Vulgaris (Thyme) Extract', 'Aspalathus Linearis Extract']
--------------------------------------------------
Product: 10.0% | Flawless Brightly Serum


            Dr Sam Bunting
Link: https://inkeedecoder.com/products/dr-sam-bunting-flawless-brightly-serum
Jumlah ingredient: 18
Ingredient: ['Aqua (Water)', 'Azelaic Acid 10.0%', 'Caprylic/\u200bCapric Triglyceride', 'Niacinamide 5.0%', 'Dicaprylyl Carbonate', 'Ascorbyl Glucoside 2.0%', 'Cetearyl Alcohol', 'Glycerin', 'Glyceryl Stearate SE', 'Cetearyl Olivate', 'Bakuchiol 1.0%', 'Sorbitan Olivate', 'Benzyl Alcohol', 'Xanthan Gum', 'Phenoxyethanol', 'Sodium Hydroxide', 'Disodium EDTA', 'Dehydroacetic Acid']
--------------------------------------------------
Product: 10.0% | Azelaic Acid Suspension 10%


            The Ordinary
Link: https://inkeedecoder.com/products/the-ordinary-azelaic-acid-suspension-10
Jumlah ingredient: 17
Ingredient: ['Aqua (Water)', 'Isodecyl Neopentanoate', 'Dimethicone', 'Azelaic Acid 10.0%', 'Dimethicone/\u200bBis-Isobutyl PPG-20 Crosspolymer', 'Dimethyl Isosorbide', 'Hydroxyethyl Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Polysilicone-11', 'Isohexadecane', 'Tocopherol', 'Trisodium Ethylenediamine Disuccinate', 'Isoceteth-20', 'Polysorbate 60', 'Triethanolamine', 'Ethoxydiglycol', 'Phenoxyethanol', 'Chlorphenesin']
--------------------------------------------------
Product: 5.0% | Flawless Neutralising Gel


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-neutralising-gel
Jumlah ingredient: 11
Ingredient: ['Aqua (Water)', 'Propylene Glycol', 'Ammonium Polyacryloyldimethyl Taurate', 'Azelaic Acid 5.0%', 'Squalane 5.0%', 'Salicylic Acid 2.0%', 'Glyceryl Stearate', 'Disodium EDTA', 'PEG-100 Stearate', 'Sodium Hydroxide', 'Bakuchiol 0.5%']
--------------------------------------------------
Product: 5.0% | Flawless Nightly Serum


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-nightly-serum
Jumlah ingredient: 20
Ingredient: ['Aqua (Water/\u200bEau)', 'Butylene Glycol', 'Niacinamide 10.0%', 'Azelaic Acid 5.0%', 'Dicaprylyl Carbonate', 'Glycerin', 'Ethoxydiglycol', 'Cetearyl Alcohol', 'Dimethyl Isosorbide', 'Bakuchiol 1.0%', 'Tapioca Starch', 'Benzyl Alcohol', 'Allantoin', 'Sodium Stearoyl Glutamate', 'Xanthan Gum', 'Phenoxyethanol', 'Hydroxypinacolone Retinoate 0.2%', 'Disodium EDTA', 'Dehydroacetic Acid', 'Polymethylsilsesquioxane']
--------------------------------------------------
Product: 1.0% | Flawless Brightly Serum


            Dr Sam Bunting
Link: https://inkeedecoder.com/products/dr-sam-bunting-flawless-brightly-serum
Jumlah ingredient: 18
Ingredient: ['Aqua (Water)', 'Azelaic Acid 10.0%', 'Caprylic/\u200bCapric Triglyceride', 'Niacinamide 5.0%', 'Dicaprylyl Carbonate', 'Ascorbyl Glucoside 2.0%', 'Cetearyl Alcohol', 'Glycerin', 'Glyceryl Stearate SE', 'Cetearyl Olivate', 'Bakuchiol 1.0%', 'Sorbitan Olivate', 'Benzyl Alcohol', 'Xanthan Gum', 'Phenoxyethanol', 'Sodium Hydroxide', 'Disodium EDTA', 'Dehydroacetic Acid']
--------------------------------------------------
Product: 1.0% | Flawless Nightly Serum


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-nightly-serum
Jumlah ingredient: 20
Ingredient: ['Aqua (Water/\u200bEau)', 'Butylene Glycol', 'Niacinamide 10.0%', 'Azelaic Acid 5.0%', 'Dicaprylyl Carbonate', 'Glycerin', 'Ethoxydiglycol', 'Cetearyl Alcohol', 'Dimethyl Isosorbide', 'Bakuchiol 1.0%', 'Tapioca Starch', 'Benzyl Alcohol', 'Allantoin', 'Sodium Stearoyl Glutamate', 'Xanthan Gum', 'Phenoxyethanol', 'Hydroxypinacolone Retinoate 0.2%', 'Disodium EDTA', 'Dehydroacetic Acid', 'Polymethylsilsesquioxane']
--------------------------------------------------
Product: 1.0% | 1% Bakuchiol Serum


            Revolution Skincare
Link: https://inkeedecoder.com/products/revolution-skincare-1-bakuchiol-serum
Jumlah ingredient: 15
Ingredient: ['Aqua (Water, Eau)', 'Propanediol', 'Isopropyl Myristate', 'Caprylic/\u200bCapric Triglyceride', 'Vitis Vinifera Seed Oil', 'Bakuchiol 1.0%', 'Phenoxyethanol', 'Polyacrylamide', 'Xanthan Gum', 'C13-14 Isoparaffin', 'Titanium Dioxide', 'Laureth-7', 'Ethylhexylglycerin', 'Ci 17200 (Red 33)', 'Ci 42090 (Blue 1)']
--------------------------------------------------
Product: 0.5% | Flawless Neutralising Gel


            Dr. Sam Bunting Skincare
Link: https://inkeedecoder.com/products/dr-sam-bunting-skincare-flawless-neutralising-gel
Jumlah ingredient: 11
Ingredient: ['Aqua (Water)', 'Propylene Glycol', 'Ammonium Polyacryloyldimethyl Taurate', 'Azelaic Acid 5.0%', 'Squalane 5.0%', 'Salicylic Acid 2.0%', 'Glyceryl Stearate', 'Disodium EDTA', 'PEG-100 Stearate', 'Sodium Hydroxide', 'Bakuchiol 0.5%']
--------------------------------------------------
Product: SENTÉ Cysteamine Hsa Pigment & Tone Corrector
Link: https://inkeedecoder.com/products/sente-cysteamine-hsa-pigment-tone-corrector
Jumlah ingredient: 38
Ingredient: ['Water/\u200bAqua/\u200bEau', 'Dimethicone', 'Caprylic/\u200bCapric Triglyceride', 'Isononyl Isononanoate', 'Cysteamine', 'Hci', 'Niacinamide', 'C12-16 Alcohols', 'Lecithin', 'Tetrahexyldecyl Ascorbate', 'Cetearyl Alcohol', 'Glycerin', 'Heparan Sulfate', 'Polysilicone-11', 'Tocopheryl Acetate', 'Hydrogenated Lecithin', 'Palmitic Acid', 'Hydroxyacetophenone', 'Diethylhexyl Syringylidenemalonate', 'Polyacrylate-13', 'Butylene Glycol', 'Epilobium Angustifolium Flower/\u200bLeaf/\u200bStem Extract', 'Mannitol', 'Ergothioneine', 'Sclerotium Gum', 'Lysolecithin', 'Polyisobutene', 'Decyl Glucoside', 'Pullulan', 'Aminomethyl Propanol', 'Xanthan Gum', 'Sodium Stearoyl Glutamate', 'Fragrance', 'Polysorbate 20', 'Propanediol', 'Ethylhexylglycerin', 'Phenoxyethanol', 'Disodium EDTA']
--------------------------------------------------
Product: DermDoc Niacinamide And Sodium Hyaluronate Serum
Link: https://inkeedecoder.com/products/dermdoc-niacinamide-and-sodium-hyaluronate-serum
Jumlah ingredient: 16
Ingredient: ['Niacinamide', 'Sodium Hyaluronate Crosspolymer', 'Ellagic Acid', 'Aquaxyl', 'Xylitylglucoside', 'Anhydroxylitol', 'Xylitol', 'Aqua', 'Sodium Gluconate', 'Glycerin', 'Xanthan Gum', 'Cetearyl Olivate', 'Sorbitan Olivate', 'Sodium Hydroxide', 'Phenoxyethanol', 'Perfume']
--------------------------------------------------
Product: Cellex-C Skin Hydration Complex
Link: https://inkeedecoder.com/products/cellex-c-skin-hydration-complex
Jumlah ingredient: 6
Ingredient: ['Water (Aqua)', 'Hyaluronic Acid', 'Proline', 'Glycine', 'Ellagic Acid', 'Phenoxyethanol']
--------------------------------------------------
Product: Dermalosophy Pigmento New Skin
Link: https://inkeedecoder.com/products/dermalosophy-pigmento-new-skin
Jumlah ingredient: 24
Ingredient: ['Water', 'Sebacic Acid', 'Acetyl Glucosamine', 'Cinnamic Acid', 'Ellagic Acid', 'Ferulic Acid', 'Tranexamic Acid', 'Turmeric (Curcuma Longa) Extract', 'Acetic Acid', 'Histidine', 'Ceteareth-20', 'Cetyl Palmitate', 'Octyldecanol', 'Decyl Oleate', 'Phytic Acid', 'Ascorbyl Methylsilanol Pectinate', 'Camellia Sinensis Extract', 'Acrylates/\u200bC10-30 Alkyl Acrylate Crosspolymer', 'Triethanolamine', 'Thiotaurine', 'Phenoxyethanol', 'Ethylhexylglycerin', 'Glyceryl Stearate', 'PEG-100 Stearate']
--------------------------------------------------
Product: Transparent lab Gentle Rejuvenation Serum
Link: https://inkeedecoder.com/products/transparent-lab-gentle-rejuvenation-serum
Jumlah ingredient: 23
Ingredient: ['Aqua (Water)', 'Propanediol', 'Glycerin', 'Niacinamide', 'Ellagic Acid', 'Hydrogenated Phosphatidylcholine', 'Retinol', 'Ethylhexylglycerin', 'Sodium Phytate', 'Phosphatidylcholine', 'Mannitol', 'Lecithin', 'Cholesterol', 'BHA', 'Xanthan Gum', 'Sodium Acrylates Copolymer', 'Decyl Glucoside', 'BHT', 'Sodium Chloride', 'Citric Acid', 'Sodium Benzoate', 'Potassium Sorbate', 'Phenoxyethanol']
--------------------------------------------------
Product: Transparent lab Super C Serum
Link: https://inkeedecoder.com/products/transparent-lab-super-c-serum
Jumlah ingredient: 20
Ingredient: ['Aqua (Water)', 'Propanediol', 'Glycerin', 'Ascorbyl Glucoside', 'Ellagic Acid', 'Hyaluronic Acid', 'Phosphatidylcholine', 'Mannitol', 'Sodium Hyaluronate', 'Hydrogenated Phosphatidylcholine', 'Decyl Glucoside', 'Dehydroxanthan Gum', 'Sodium Phytate', 'Cholesterol', 'Phenoxyethanol', 'Ethylhexylglycerin', 'Xanthan Gum', 'Potassium Sorbate', 'Sodium Benzoate', 'Sodium Chloride']
--------------------------------------------------
Product: Transparent lab Super C Serum: Anti-aging Serum Mit Vitamin C
Link: https://inkeedecoder.com/products/transparent-lab-super-c-serum-anti-aging-serum-mit-vitamin-c
Jumlah ingredient: 22
Ingredient: ['Aqua (Water)', 'Propanediol', 'Glycerin', 'Ascorbyl Glucoside', 'Hyaluronic Acid', 'Ellagic Acid', 'Sodium Hyaluronate', 'Mannitol', 'Phosphatidylcholine', 'Cholesterol', 'Dehydroxanthan Gum', 'Hydrogenated Phosphatidylcholine', 'Decyl Glucoside', 'Xanthan Gum', 'Sodium Phytate', 'Sodium Chloride', 'Sodium Benzoate', 'Potassium Sorbate', 'Ethylhexylglycerin', 'Phenoxyethanol', 'Triethanolamine', 'Tocopherol']
--------------------------------------------------
Product: Umoua Polar Lights Extreme Brightening Concentrate Serum
Link: https://inkeedecoder.com/products/umoua-polar-lights-extreme-brightening-concentrate-serum
Jumlah ingredient: 23
Ingredient: ['Water', 'Chlorella Ferment', 'Tetrahexyldecyl Ascorbate', 'Aminopropyl Kojyl Phosphate', 'Tranexamic Acid', 'Potassium Methoxysalicylate', 'Ellagic Acid', 'Dimethicone/\u200bVinyl Dimethicone Crosspolymer', 'Citrus Medica Limonum Fruit Extract', 'Leontopodium Alpinum Extract', 'Hydroxycinnamic Acid', 'Taurine', 'Glycyrrhiza Glabra Root Extract', 'PEG/\u200bPPG/\u200bPolybutylene Glycol-8/\u200b5/\u200b3 Glycerin', 'Pullulan', 'Coix Lacryma-Jobi Ma-Yuen Seed Extract', 'Inositol', 'Hydroxyacetophenone', 'Caprylyl Glycol', 'Ethylhexylglycerin', 'Diethylhexyl Syringylidenemalonate', 'Disodium EDTA', 'Pelargonium Graveolens Oil']
--------------------------------------------------
Product: Conscious Chemist Acne Face Wash
Link: https://inkeedecoder.com/products/concious-chemist-acne-face-wash
Jumlah ingredient: 19
Ingredient: ['Demineralized Water', 'Coco-Glucoside', 'Decyl Glucoside', 'CAPB', 'Glycerine', 'Salicylic Acid', 'Glycolic Acid', 'Ellagic Acid', 'Xanthan Gum', 'Punica Granatum Seed Oil (Pomegranate Oil)', 'Propylene Glycol', 'Glycyrrhiza Glabra', 'Linden Extract (Licorice Extract)', 'Centella Asiatica Extract', 'Polysorbate 20', 'Tea', 'Citrullus Lanatus (Watermelon) Extract', 'EDTA', 'Phenoxyethanol']
--------------------------------------------------
Product: Derma-ceutix Hydrating Vitamin Mist
Link: https://inkeedecoder.com/products/derma-ceutix-hydrating-vitamin-mist
Jumlah ingredient: 17
Ingredient: ['Water', 'Magnesium', 'Aspartame', 'Zinc Gluconate', 'Copper Gluconate', 'Alcohol Denat', 'Glycolic Acid', 'Dimethyl MEA', 'Ellagic Acid', 'Tetrahexyldecyl Ascorbate', 'Tocotrienols', 'Tocopherol', 'Pyridoxine Hcl', 'Phenoxyethanol', 'Caprylyl Glycol', 'Sorbic Acid', 'Fragrance']
--------------------------------------------------
Product: PHARMACERIS T Azeloacne Azelaic Acid 20% Cream
Link: https://inkeedecoder.com/products/pharmaceris-t-azeloacne-azelaic-acid-20-cream
Jumlah ingredient: 28
Ingredient: ['Aqua (Water)', 'Azelaic Acid', 'Propylene Glycol', 'Glyceryl Stearate', 'Cetearyl Ethylhexanoate', 'Glycerin', 'PEG-30 Stearate', 'Lecithin', 'Ellagic Acid', 'Glabridin', 'Honokiol', 'Magnolol', 'Isopropyl Myristate', 'Isohexadecane', 'Cetearyl Alcohol', 'Cetyl Palmitate', 'Cocoglycerides', 'Sodium Acrylate/\u200bSodium Acryloyldimethyl Taurate Copolymer', 'Polysorbate 80', 'Cellulose', 'Hydroxyethylcellulose', 'Sorbitan Oleate', 'Ethylhexylglycerin', 'Benzoic Acid', 'Benzyl Alcohol', 'Potassium Sorbate', 'Sodium Benzoate', 'Dehydroacetic Acid']
--------------------------------------------------
Product: Then I Met You The Giving Essence
Link: https://inkeedecoder.com/products/then-i-met-you-the-giving-essence
Jumlah ingredient: 41
Ingredient: ['Galactomyces Ferment Filtrate', 'Aspergillus Ferment Extract Filtrate', 'Saccharomyces Ferment Filtrate', 'Propanediol', 'Niacinamide', 'Butylene Glycol', '1,2-Hexanediol', 'Aloe Barbadensis Leaf Extract', 'Ellagic Acid', 'Aronia Melanocarpa Fruit Extract', 'Polyglutamic Acid', 'Glycerin', 'Corallina Officinalis Extract', 'Sodium Hyaluronate', 'Morus Alba Root Extract', 'Allantoin', 'Ocimum Sanctum Leaf Extract', 'Ribes Nigrum (Black Currant) Fruit Extract', 'Rubus Coreanus Fruit Extract', 'Lycium Chinense Fruit Extract', 'Curcuma Longa (Turmeric) Root Extract', 'Glycyrrhiza Uralensis (Licorice) Root Extract', 'Rubus Fruticosus (Blackberry) Fruit Extract', 'Rubus Idaeus (Raspberry) Fruit Extract', 'Betaine', 'Vaccinium Myrtillus Fruit Extract', 'Aristotelia Chilensis Fruit Extract', 'Euterpe Oleracea Fruit Extract', 'Vaccinium Angustifolium (Blueberry) Fruit Extract', 'Aloe Barbadensis Flower Extract', 'Solanum Melongena (Eggplant) Fruit Extract', 'Gardenia Jasminoides Fruit Extract', 'Sodium Polyacryloyldimethyl Taurate', 'Ethylhexylglycerin', 'Melia Azadirachta Leaf Extract', 'Melia Azadirachta Flower Extract', 'Xanthan Gum', 'Coccinia Indica Fruit Extract', 'Portulaca Oleracea Extract', 'Water', 'Methylpropanediol']
--------------------------------------------------
Product: Then I Met You The Giving Essence

Hal tersebut dilakukan untuk menambahkan kolom `ingredient` yang sebelumnya hanya terdapat 1 untuk setiap kelompok produk. 

Oleh karena itu, scraping data dilakukan agar kolom ingredient per product lebih lengkap dan detail.

Pada masalah kulit Darkspots. Setiap produk mempunyai jumlah yang ingredients yang bervariasi. Satu produk mempunyai sekitar 2 - 47 ingredients yang berbeda-beda.

##### Penyimpanan data

In [6]:
df.to_csv("Skincare Dataset/Dark-Spots Product.csv", index=False)

df.head(10)

,problem,ingredient,product name,product link
0,dark spots,"Avobenzone 3.0%, Octinoxate 7.5%, Octisalate 5...",0.3% | Enlighten Skin Brightener Spf35\n ...,https://inkeedecoder.com/products/neostrata-en...
1,dark spots,"Avobenzone 3.0%, Octinoxate 7.5%, Octisalate 5...",8.0% | Enlighten Skin Brightener Spf35\n ...,https://inkeedecoder.com/products/neostrata-en...
2,dark spots,"Water, Niacinamide 5.0%, Arbutin 2.0%, Acetyl ...",2.0% | Lab. Restoring Brightening Serum\n ...,https://inkeedecoder.com/products/purid-lab-re...
3,dark spots,"Water, Butylene Glycol, Propanediol, Glycerin,...",2.0% | Alpha Arbutin Brightening Serum\n ...,https://inkeedecoder.com/products/inkey-list-a...
4,dark spots,"Propanediol, Ascorbic Acid 8.0%, Alpha-Arbutin...",2.0% | Ascorbic Acid 8% + Alpha Arbutin 2%\n ...,https://inkeedecoder.com/products/the-ordinary...
5,dark spots,"Water, Azelaic Acid 20.0%, Ascorbic Acid, Toco...",20.0% | Azelaic Acid\n \n\n ...,https://inkeedecoder.com/products/derma-forte-...
6,dark spots,"Aqua, Propylene Glycol, Azelaic Acid 15.0%, Te...",15.0% | Azelaic Acid Control Facial Acne Gel\n...,https://inkeedecoder.com/products/aisuanis-emp...
7,dark spots,"Aqua, Dipropylene Glycol, Cyclopentasiloxane, ...",10.0% | Empowerment Azelaic Acid Sebamed Clear...,https://inkeedecoder.com/products/aisuanis-emp...
8,dark spots,"Aqua (Water), Propylene Glycol, Azelaic Acid 1...",10.0% | Professional 10% Azelaic Acid Face Ser...,https://inkeedecoder.com/products/bielenda-pro...
9,dark spots,"Aloe Barbadensis Leaf Extract, Propylene Glyco...",10.0% | Azelaic Acid 10% Serum\n \n\n ...,https://inkeedecoder.com/products/cos-de-baha-...

Data yang sudah di scraping disimpan dan diperbarui ke dalam bentuk csv agar dapat di masukkan ke database supabase

Terlihat dari 10 hasil awal yang di tampilkan setiap produk memiliki ingredient yang berbeda-beda