## Import Libraries

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, text

## Loading data

Membuat data base untuk setiap table

In [ ]:
df_acne = pd.read_csv("Skincare Dataset/Anti-Acne Product.csv")
df_comedo = pd.read_csv("Skincare Dataset/Comedo Product.csv")
df_darkspots = pd.read_csv("Skincare Dataset/Dark-Spots Product.csv")
df_pores = pd.read_csv("Skincare Dataset/pores_data.csv")
df_wrinkle = pd.read_csv("Skincare Dataset/wrinkle.csv")

Menggabungkan semua database yang berbentuk table (csv)

In [3]:
df = pd.concat(
    [df_acne, df_comedo, df_darkspots, df_pores, df_wrinkle],
    ignore_index=True
)
df

,problem,ingredient,product name,product link
0,acne,"Aqua, Caprylic/​Capric Triglyceride, Decyl Ole...",Arkana Neuro Gaba And Nano Cream,https://inkeedecoder.com/products/arkana-neuro...
1,acne,"Water, Glycerin, Butylene Glycol, 1,2-Hexanedi...",Isntree Onion Newpair Soothing Mask,https://inkeedecoder.com/products/isntree-onio...
2,acne,"Adapalene 0.1%, Carbomer Homopolymer, Edetate ...",0.1% | Effaclar Adapalene Gel 0.1% Acne Treatm...,https://inkeedecoder.com/products/la-roche-pos...
3,acne,"Water, Azelaic Acid 20.0%, Ascorbic Acid, Toco...",20.0% | Azelaic Acid\n \n\n ...,https://inkeedecoder.com/products/derma-forte-...
4,acne,"Aqua, Propylene Glycol, Azelaic Acid 15.0%, Te...",15.0% | Azelaic Acid Control Facial Acne Gel\n...,https://inkeedecoder.com/products/aisuanis-emp...
...,...,...,...,...
1999,wrinkles,"Aqua (Water), Glycerin, Cetyl Alcohol, Ceteary...",Helia-D Professional Vitamin C Lifting And Rad...,https://inkeedecoder.com/products/helia-d-prof...
2000,wrinkles,"Aqua(Water), Methylpropanediol, 1,2-Hexanediol...",Cremorlab Hydra Balancing Toner,https://inkeedecoder.com/products/cremorlab-hy...
2001,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Oleic Rapid Recovery Milk,https://inkeedecoder.com/products/strivectin-o...
2002,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Double Fix™ For Lips Plumping & Ver...,https://inkeedecoder.com/products/strivectin-d...
2003,wrinkles,"Water, Glycerin, Butylene Glycol, Isopropyl My...",DEMAR3 Rem-Rose 25 Shield Crème,https://inkeedecoder.com/products/demar3-rem-r...

Terlihat Setelah digabung dari beberapa csv terdapat 2004 baris dan 4 kolom yang berisi permasalahan kulit, ingredient, nama product dan link produk.

Mengganti nama kolom

In [4]:
df = df.rename(columns={
    "product name": "product_name",
    "product link": "product_link"
})

df.tail(10)

,problem,ingredient,product_name,product_link
1994,wrinkles,"Water (Aqua), Cyclopentasiloxane, Cetearyl Iso...",Zo skin health Brightenex™ 0.5% Retinol,https://inkeedecoder.com/products/zo-skin-heal...
1995,wrinkles,"Water/​Aqua/​Eau, Glycerin, Hydroxyethyl Acryl...",DRMTLGY Hydra-fader,https://inkeedecoder.com/products/drmtlgy-hydr...
1996,wrinkles,"Aqua, Octyldodecanol, Butylene Glycol, Ceteary...",Evershine Bright Day Cream,https://inkeedecoder.com/products/evershine-br...
1997,wrinkles,"Aloe Barbadensis Leaf Juice, Butylene Glycol, ...",SKINMADE Niacinamide + Allantoin Serum,https://inkeedecoder.com/products/skinmade-nia...
1998,wrinkles,"Aqua (Water), Glycerin, Cetyl Alcohol, Ceteary...",Helia-D Professional Tens'up Lifting Cream,https://inkeedecoder.com/products/helia-d-prof...
1999,wrinkles,"Aqua (Water), Glycerin, Cetyl Alcohol, Ceteary...",Helia-D Professional Vitamin C Lifting And Rad...,https://inkeedecoder.com/products/helia-d-prof...
2000,wrinkles,"Aqua(Water), Methylpropanediol, 1,2-Hexanediol...",Cremorlab Hydra Balancing Toner,https://inkeedecoder.com/products/cremorlab-hy...
2001,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Oleic Rapid Recovery Milk,https://inkeedecoder.com/products/strivectin-o...
2002,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Double Fix™ For Lips Plumping & Ver...,https://inkeedecoder.com/products/strivectin-d...
2003,wrinkles,"Water, Glycerin, Butylene Glycol, Isopropyl My...",DEMAR3 Rem-Rose 25 Shield Crème,https://inkeedecoder.com/products/demar3-rem-r...

Membersihkan data yang sudah digabungkan

In [5]:
df.isnull().sum()

problem         0
ingredient      0
product_name    0
product_link    0
dtype: int64

Terlihat tidak ada yang data `null` dalam table tersebut.

In [ ]:
df.duplicated().sum()

18

Terdapat 18 duplikasi pada database tersebut.

In [7]:
df[df.duplicated()]

,problem,ingredient,product_name,product_link
186,acne,"Melaleuca Alternifolia (Tea Tree) Leaf Oil, Sa...",Dot & Key Skin Clarifying Face Serum,https://inkeedecoder.com/products/dot-key-skin...
496,comedo,"Pure Calcium Bentonite Clay, Activated Carbon",Apotheke Detoxifying Face Mask,https://inkeedecoder.com/products/apotheke-det...
757,comedo,"Sulfur (6%), Water, Kaolin, Glycereth-26, Lino...",Proactiv Skin Purifying Mask,https://inkeedecoder.com/products/proactiv-ski...
1076,dark spots,"Hydroquinone (2%), Kojic Acid, Arbutin, Ethoxy...",AziMD Skincare Dermabright Pads,https://inkeedecoder.com/products/azimd-skinca...
1079,dark spots,"Hydroquinone (3.9%), Kojic Acid (2%), Certifie...",ClearChoice Enlighten,https://inkeedecoder.com/products/clearchoice-...
1124,dark spots,"Aqua (Water), Azelaic Acid, Propylene Glycol, ...",PHARMACERIS T Azeloacne Azelaic Acid 20% Cream,https://inkeedecoder.com/products/pharmaceris-...
1130,dark spots,"Kojic Acid, Licorice Extract, Alpha-Arbutin, V...",Interpharma Spleet Whitening,https://inkeedecoder.com/products/interpharma-...
1173,dark spots,"Propanediol, Resveratrol 3.0%, Ferulic Acid 3.0%",3.0% | Resveratrol 3% + Ferulic Acid 3%\n ...,https://inkeedecoder.com/products/the-ordinary...
1706,wrinkles,"Water, Acetyl Hexapeptide-8, Acetyl Glutamyl H...",CELLBONE Hyper Peptides,https://inkeedecoder.com/products/cellbone-hyp...
1723,wrinkles,"Hyaluronic Acid, Acetyl Hexapeptide-8, Dipalmi...",Le Mieux Bio Cell Rejuvenating Cream,https://inkeedecoder.com/products/le-mieux-bio...
1724,wrinkles,"Hyaluronic Acid, Acetyl Hexapeptide-8, Dipalmi...",Le Mieux Bio Cell Rejuvenating Cream,https://inkeedecoder.com/products/le-mieux-bio...
1725,wrinkles,"Hyaluronic Acid, Acetyl Hexapeptide-8, Dipalmi...",Le Mieux Bio Cell Rejuvenating Cream,https://inkeedecoder.com/products/le-mieux-bio...
1726,wrinkles,"Hyaluronic Acid, Acetyl Hexapeptide-8, Dipalmi...",Le Mieux Essence Moisturizer,https://inkeedecoder.com/products/le-mieux-ess...
1739,wrinkles,"Hydrolyzed Hibiscus Esculentus Extract, Acetyl...",Suiphar Peptix,https://inkeedecoder.com/products/suiphar-peptix
1844,wrinkles,"Water, Acetyl Hexapeptide-8, Butylene Glycol, ...",Skinwell Derm (Dr. Ava Khosraviani) Total Eye,https://inkeedecoder.com/products/skinwell-der...
1903,wrinkles,"Aqua, Acetyl Hexapeptide-8, Pentapeptide-18, P...",Dermaten Firming Power Serum,https://inkeedecoder.com/products/dermaten-fir...
1909,wrinkles,"Distilled Water, Acetyl Hexapeptide-8, Palmito...",Dermaceutic Peptidos De Cobre Suero Anti-edad,https://inkeedecoder.com/products/dermaceutic-...
1928,wrinkles,Human Adipose Derived Stem Cell Conditioned Me...,NuGene Eye Serum,https://inkeedecoder.com/products/nugene-eye-s...

berdasarkan hasil tersebut dapat disimpulkan bahwa ada beberapa yang harus di hapus duplikasinya karena memiliki nama product yang sama.

In [8]:
df = df.drop_duplicates(
    subset=["problem", "ingredient", "product_name", "product_link"],
    keep="first"
)

df = df.reset_index(drop=True)
df

,problem,ingredient,product_name,product_link
0,acne,"Aqua, Caprylic/​Capric Triglyceride, Decyl Ole...",Arkana Neuro Gaba And Nano Cream,https://inkeedecoder.com/products/arkana-neuro...
1,acne,"Water, Glycerin, Butylene Glycol, 1,2-Hexanedi...",Isntree Onion Newpair Soothing Mask,https://inkeedecoder.com/products/isntree-onio...
2,acne,"Adapalene 0.1%, Carbomer Homopolymer, Edetate ...",0.1% | Effaclar Adapalene Gel 0.1% Acne Treatm...,https://inkeedecoder.com/products/la-roche-pos...
3,acne,"Water, Azelaic Acid 20.0%, Ascorbic Acid, Toco...",20.0% | Azelaic Acid\n \n\n ...,https://inkeedecoder.com/products/derma-forte-...
4,acne,"Aqua, Propylene Glycol, Azelaic Acid 15.0%, Te...",15.0% | Azelaic Acid Control Facial Acne Gel\n...,https://inkeedecoder.com/products/aisuanis-emp...
...,...,...,...,...
1981,wrinkles,"Aqua (Water), Glycerin, Cetyl Alcohol, Ceteary...",Helia-D Professional Vitamin C Lifting And Rad...,https://inkeedecoder.com/products/helia-d-prof...
1982,wrinkles,"Aqua(Water), Methylpropanediol, 1,2-Hexanediol...",Cremorlab Hydra Balancing Toner,https://inkeedecoder.com/products/cremorlab-hy...
1983,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Oleic Rapid Recovery Milk,https://inkeedecoder.com/products/strivectin-o...
1984,wrinkles,"Aqua (Water, Eau), Glycerin, Myristyl Nicotina...",StriVectin Double Fix™ For Lips Plumping & Ver...,https://inkeedecoder.com/products/strivectin-d...
1985,wrinkles,"Water, Glycerin, Butylene Glycol, Isopropyl My...",DEMAR3 Rem-Rose 25 Shield Crème,https://inkeedecoder.com/products/demar3-rem-r...

Setelah dihapus duplikasinya tersisa 1986 nama product.

#### menyimpan data

In [9]:
df.to_csv("raw_data.csv", index=False)

In [10]:
df_clean = df.copy()

### Final Cleaning

Kolom Problem

In [11]:
df_clean["problem"].str.strip().str.lower()
display(df_clean["problem"])

0           acne
1           acne
2           acne
3           acne
4           acne
          ...
1981    wrinkles
1982    wrinkles
1983    wrinkles
1984    wrinkles
1985    wrinkles
Name: problem, Length: 1986, dtype: object

#### Membersihkan Kolom Product Name

In [12]:
df_clean["product_name"] = (
df_clean["product_name"].str.replace(r"^\s*\d+\.?\d*%\s*\|?\s*", "", regex=True)
.str.replace(r"\s+", " ", regex=True)
.str.strip()
)
df_clean = df_clean[~df_clean["product_name"].str.contains("Next page >>", case=False, na=False)]
df_clean = df_clean[~df_clean["product_name"].str.contains("Show all >>", case=False, na=False)]

df_clean = df_clean.reset_index(drop=True)

display(df_clean["product_name"])

0                        Arkana Neuro Gaba And Nano Cream
1                     Isntree Onion Newpair Soothing Mask
2       Effaclar Adapalene Gel 0.1% Acne Treatment La ...
3                                Azelaic Acid Derma Forte
4           Azelaic Acid Control Facial Acne Gel Aisuanis
                              ...
1940    Helia-D Professional Vitamin C Lifting And Rad...
1941                      Cremorlab Hydra Balancing Toner
1942                 StriVectin Oleic Rapid Recovery Milk
1943    StriVectin Double Fix™ For Lips Plumping & Ver...
1944                      DEMAR3 Rem-Rose 25 Shield Crème
Name: product_name, Length: 1945, dtype: object

Terlihat nama produk menjadi lebih rapi dan mudah di baca

Membersihkan kolom `ingredient`

In [13]:
def clean_ingredients(text):
    ingredients = text.split(",")

    cleaned = []

    for i in ingredients:
        i = i.strip()
        cleaned.append(i)

    cleaned =  list(dict.fromkeys(cleaned))

    cleaned = cleaned[:10]

    return ", ".join(cleaned)

df_clean["ingredient"] = df["ingredient"].apply(clean_ingredients)
df_clean

,problem,ingredient,product_name,product_link
0,acne,"Aqua, Caprylic/​Capric Triglyceride, Decyl Ole...",Arkana Neuro Gaba And Nano Cream,https://inkeedecoder.com/products/arkana-neuro...
1,acne,"Water, Glycerin, Butylene Glycol, 1, 2-Hexaned...",Isntree Onion Newpair Soothing Mask,https://inkeedecoder.com/products/isntree-onio...
2,acne,"Adapalene 0.1%, Carbomer Homopolymer, Edetate ...",Effaclar Adapalene Gel 0.1% Acne Treatment La ...,https://inkeedecoder.com/products/la-roche-pos...
3,acne,"Water, Azelaic Acid 20.0%, Ascorbic Acid, Toco...",Azelaic Acid Derma Forte,https://inkeedecoder.com/products/derma-forte-...
4,acne,"Aqua, Propylene Glycol, Azelaic Acid 15.0%, Te...",Azelaic Acid Control Facial Acne Gel Aisuanis,https://inkeedecoder.com/products/aisuanis-emp...
...,...,...,...,...
1940,wrinkles,"Water, Glycerin, Cyclopentasiloxane, Glycereth...",Helia-D Professional Vitamin C Lifting And Rad...,https://inkeedecoder.com/products/helia-d-prof...
1941,wrinkles,"Water, Butyrospermum Parkii (Shea Butter), Lac...",Cremorlab Hydra Balancing Toner,https://inkeedecoder.com/products/cremorlab-hy...
1942,wrinkles,"Aqua, Oenothera Biennis (Evening Primrose) Oil...",StriVectin Oleic Rapid Recovery Milk,https://inkeedecoder.com/products/strivectin-o...
1943,wrinkles,"Aqua, Alcohol, Caprylic/​Capric Triglyceride, ...",StriVectin Double Fix™ For Lips Plumping & Ver...,https://inkeedecoder.com/products/strivectin-d...
1944,wrinkles,"Aqua, Chloroacetic Acid, Propylene Glycol, Koj...",DEMAR3 Rem-Rose 25 Shield Crème,https://inkeedecoder.com/products/demar3-rem-r...

Karena jumlah ingredient setiap product bervariasi, maka untuk kerapian data setiap produk dibatasi hanya menggunakkan 10 ingredient pertama.

#### Cek duplikasi

In [14]:
df_clean.isnull().sum()

problem         0
ingredient      0
product_name    0
product_link    0
dtype: int64

Terlihat setelah di rapihkan dan di batasi ingredientnya tidak ada `null` dalam data tersebut.

#### Cek Duplikasi

In [15]:
df_clean.duplicated().sum()

0

Terlihat juga bahwa tidak ada data yang sama dalam satu table tersebut.

Cek kolom dan baris

In [16]:
df_clean.shape

(1945, 4)

Terlihat hasil dari final cleaning terdapat 1945 baris dan 4 kolom dalam database tersebut

#### Penyimpanan Data

In [17]:
df_clean.to_csv("data_clean.csv", index=False)

Setelah final cleaning data disimpan dalam bentuk csv

## Memasukan data ke Supabase

Koneksi ke supabase

In [18]:
DATABASE_URL = "postgresql://postgres.fmaxbctcyypttddokixc:NZUxd42nuGBsmy3w@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"

engine = create_engine(DATABASE_URL)

membuat koneksi antara python dan database supabase menggunakan PostgreSQL

Testing Koneksi

In [19]:
with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

Output (1,) menunjukkan bahwa koneksi database berhasil dilakukan

Pengecekan kolom

In [20]:
df_clean.columns

Index(['problem', 'ingredient', 'product_name', 'product_link'], dtype='object')

Data memiliki 4 kolom utama yaitu `problem`, `ingredient`, `product_name`, dan `product_link`.

Pengecekkan Jumlah Data

In [21]:
len(df_clean)

1945

Setelah proses cleaning, terdapat 1.945 data yang siap dimasukkan ke database

Pembuatan fungsi upload

In [28]:
def upload_data(df_clean):
    query = text("""
        INSERT INTO skincare_recommendation
        (problem, ingredient, product_name, product_link)
        VALUES
        (:problem, :ingredient, :product_name, :product_link)
        ON CONFLICT (problem, ingredient, product_name, product_link)
        DO NOTHING
    """)

    data = df_clean[
        ["problem", "ingredient", "product_name", "product_link"]
    ].to_dict(orient="records")
    
    with engine.begin() as conn:
        result = conn.execute(query, data)

print("Data baru yang masuk:", result.rowcount)

Data baru yang masuk: 1

Fungsi upload_data() digunakan untuk memasukkan data ke tabel skincare_recommendation.

Upload Data

In [29]:
upload_data(df_clean)

Data yang sudah dibersihkan kemudian di-upload ke Supabase menggunakan fungsi upload_data(df_clean).

Penyimpanan dataframe ke tabel

In [ ]:
df.to_sql(
    "skincare_cleaned",
    con=engine,
    if_exists="replace",
    index=False
)

to_sql() digunakan untuk menyimpan dataframe ke tabel skincare_cleaned tanpa menyertakan index.